# Main config file
cassandra_config_file: /etc/cassandra/conf/cassandra.yaml
# Service file
cassandra_service_file: /etc/systemd/system/cassandra.service
# JVM Options
cassandra_jvm_options_file: /etc/cassandra/conf/jvm.options
# Log Options
cassandra_logback_xml_file: /etc/cassandra/conf/logback.xml

cluster_name: 'TestNet'
num_tokens: 32
# hints
hinted_handoff_enabled: 'true'
max_hint_window_in_ms: 10800000 # 3 hours
hinted_handoff_throttle_in_kb: 2048
max_hints_delivery_threads: 6
hints_directory: '/data/cassandra/hints'
hints_flush_period_in_ms: 10000
max_hints_file_size_in_mb: 128
hints_compression_class_name: LZ4Compressor
batchlog_replay_throttle_in_kb: 1024
#auth
authenticator: 'AllowAllAuthenticator'
authorizer: 'AllowAllAuthorizer'
permissions_validity_in_ms: 2000
permissions_update_interval_in_ms: 1000
role_manager: CassandraRoleManager
roles_validity_in_ms: 2000
permissions_validity_in_ms: 2000
credentials_validity_in_ms: 2000

partitioner: 'org.apache.cassandra.dht.Murmur3Partitioner'

data_file_directories: '/data/cassandra/data'
commitlog_directory: '/data/cassandra/commitlog'
disk_failure_policy: 'stop'
commit_failure_policy: 'stop'
key_cache_save_period: 14400
key_cache_keys_to_save: 100
row_cache_size_in_mb: 0
row_cache_save_period: 0
row_cache_keys_to_save: 100
counter_cache_save_period: 7200
counter_cache_keys_to_save: 100

saved_caches_directory: '/var/lib/cassandra/saved_caches'
commitlog_sync: 'periodic'
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider_class_name: 'org.apache.cassandra.locator.SimpleSeedProvider'
seeds: "{{ groups['cassandra-servers'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
concurrent_reads: 32
concurrent_writes: 32
concurrent_counter_writes: 32

file_cache_size_in_mb: 512
memtable_heap_space_in_mb: 2048
memtable_offheap_space_in_mb: 2048
memtable_cleanup_threshold: 0.11
memtable_allocation_type: 'heap_buffers'
commitlog_total_space_in_mb: 8192
memtable_flush_writers: 8
index_summary_resize_interval_in_minutes: 60
trickle_fsync: false
trickle_fsync_interval_in_kb: 10240
storage_port: 7000
ssl_storage_port: 7001
# TODO:
# listen_interface: 'eth0'
listen_address: "{{ ansible_eth0['ipv4']['address'] }}"
rpc_address: "{{ ansible_eth0['ipv4']['address'] }}"
# ansible_interfaces
#
start_native_transport: 'true'
native_transport_port: 9042
native_transport_max_threads: 128
native_transport_max_frame_size_in_mb: 256
